version: "3.7"

services:

  auth:
    hostname: auth
    build:
      context: .
      dockerfile: ./auth_api/Dockerfile
    ports:
      - "3001:3001"
    expose:
      - 3001  
    restart: always



  recipient:
    hostname: recipient
    build:
      context: .
      dockerfile: ./recipient_api/Dockerfile
    ports:
      - "3000:3000"
    expose:
      - 3000 
    restart: always
  
  proxy:
    hostname: proxy
    build:
      context: .
      dockerfile: ./proxy_api/Dockerfile
    ports:
      - "3002:3002"
    expose:
      - 3002
    restart: always
    links:
      - recipient
      - auth
